### ISSUE TITLE
Tutorial 5  border color

### ISSUE THREAD

**Issue by alexgg94** [giawa/opengl4tutorials#10]
I'm trying to modify tutorial 5 so that the edges of the cube are always the same color, regardless of the color of each face of the cube. Something like this:

![se1Yzm](https://github.com/giawa/opengl4tutorials/assets/15418251/2e89d49f-ed51-4e2f-973b-b8b529e6a94e)

How could I achieve this? I've been struggling for hours now

**Comment by giawa** [comment]
Hello!  There are lots of ways to accomplish this effect.  The two simplest that pop to my mind are:
1) Using a texture
2) Using a shader
Tutorial 6 covers textures.  For the shader approach I would suggest looking into GLSL tutorials.

Good luck!
