### ISSUE TITLE
Tutorial 16 is missing the enterprise.obj

### ISSUE THREAD

**Issue by delaneyj** [giawa/opengl4tutorials#2]
All tutorials run except #16 Could not find a part of the path '...\OpenGLTutorial16\OpenGLTutorial16\bin\Debug\enterprise\enterprise.obj'.  The obj doesn't seem to exist in any directory.

**Comment by giawa** [comment]
Hi delaneyj!  Sorry, I totally missed this issue.

That was just a sample .obj file that I found on the Internet.  I didn't have rights to that file, so I cannot include it in my tutorial.  There are some free files at this website:  http://www.turbosquid.com/Search/3D-Models/free/obj

Cheers,

Giawa
